title: "Alex Wa's Blog"
author: "Alex Wa"
description: "Alex Wa's blog; a mix of projects, research and life. Currently interested in RL, NLP, and ML systems."

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "alex [dot] wa [at] yale [dot] edu"
twitter_username: "_djdumpling"
github_username: "djdumpling"
linkedin_username: "alex-wa"

# Google Analytics
google_analytics: G-97R68RHKQG
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts: {}

    
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Sitemap configuration
sitemap:
  exclude: ['/archive.html']
  include: ['/test-math.html']
  lastmod: true

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
